cancelled the fail in job2

diff --git a/.github/workflows/series-jobs.yml b/.github/workflows/series-jobs.yml
--- a/.github/workflows/series-jobs.yml
+++ b/.github/workflows/series-jobs.yml
@@ -27,8 +27,8 @@ jobs:
     steps:
       - name: Output for Job 2
         run: echo "Hello from Job 2"
-      - name: make job2 fail
-        run: exit 20
+    #   - name: make job2 fail
+    #     run: exit 20
 
     
   job-3:
